# Generated by Django 3.2.15 on 2024-12-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbook',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
