# Generated by Django 3.2.15 on 2024-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_unique_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
