# Generated by Django 3.2.15 on 2024-12-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_stock_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='series_code',
            field=models.CharField(default='default_code', max_length=255),
        ),
    ]
