# Generated by Django 3.2.15 on 2024-12-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBNSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField(default=1)),
            ],
        ),
    ]
