# Generated by Django 3.2.15 on 2024-12-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20241220_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
