# Generated by Django 3.2.15 on 2024-12-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshortage',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
