# Generated by Django 3.2.15 on 2024-12-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_isbnsequence'),
        ('purchases', '0005_remove_bookshortage_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshortage',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.stock'),
        ),
    ]
