# Generated by Django 3.2.15 on 2024-12-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlevel',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditlevel',
            name='max_credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
