# Generated by Django 3.2.15 on 2024-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20241225_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlevel',
            name='max_credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
