# Generated by Django 3.2.15 on 2024-12-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_creditlevel_max_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlevel',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
