# Generated by Django 3.2.15 on 2024-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20241216_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('NOT_SHIPPED', 'NOT_SHIPPED'), ('PARTIALLY_SHIPPED', 'PARTIALLY_SHIPPED'), ('FULLY_SHIPPED', 'FULLY_SHIPPED')], default='NOT_SHIPPED', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED')], max_length=20),
        ),
    ]
