# Generated by Django 3.2.15 on 2024-12-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20241222_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='backordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='quantity_shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
