# Generated by Django 3.2.15 on 2024-12-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20241229_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='quantity_shipped',
        ),
        migrations.RemoveField(
            model_name='shippingdetail',
            name='total_quantity',
        ),
    ]
