# Generated by Django 3.2.15 on 2024-12-29 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20241229_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
