# Generated by Django 3.2.15 on 2024-12-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderdetail_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
    ]
